# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Konfigurasi Gemini Saya
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models

models:
  - name: Gemini-Flash
    provider: gemini
    model: gemini-3.6-flash
    apiKey: AQ.Ab8RN6I3_RSUCRBFMIc9pwnUeWIPqt46RP7xjC7KUubTiofNLg
    roles:
      - chat
      - edit
      - apply
      - autocomplete
